---
name: Demo App
description: >
  A Demo App which does almost nothing of any practical value.
version: 0.0.1-rancher1
category: Toy Apps
maintainer: Christoph Champ <christoph.champ@gmail.com>
license: Apache2
projectURL: https://github.com/christophchamp/rancher-cattle-demo
